### ISSUE TITLE
Bug fixes for #27

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/irrad_control#34]
- [x] Crash due to monitor tab/converter if no ADC is selected, see #30 and a299b683ee99d135b3d51f744d7add7194ddd7d7
- [x] Setub tab of server is not removed when checkbox is unchecked in setup_tab, see #31 and 0cc8b7ec4d217488634947f3cb69b04d6e887164
- [x] Converter crashes on clean-up due to missing 'positions' field in XY-stage configuration, see #33 and 48c9ccd607ed3e48597eaf84517cd9a25ba949e0
- [x] Command tab crashes on adding new positions due to missing 'positions' field in XY-stage configuration, see 0683f2b1af208a3e272f999019dd54a8ab35631b
- [x] Error due to identically labeled channels, see #29, fixed in 4780f981bb75d96bfbfc3b5d02a162fb1fcdae9a
- [x] Starting a scan should also resume the data recording if it was previously paused, see e8037dba2a7209f78c79cdb72569e13c11fa08fe
- [x] Disable the pause button in the DAQ dock when a scan is started and it is enabled, see e8037dba2a7209f78c79cdb72569e13c11fa08fe
- [x] Possible regression in fluence histogram when showing the mean fluence values, dealt with in 86c3e6cbf798cea12ad98661e6cdf02b377442cb
