### ISSUE TITLE
Improvements for #27

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/irrad_control#35]
- [x] Storing stage positions in command tab, see #9 and f4a9ef5111d9e05141f7c677edf08c171f0b4607
- [x] Automated Calculation of Time-Average and Standard-Deviation within Timeframe, see #24 and 814d288aa8275d8de1a068185c93fdb4e9574ef4
- [x] Workflow Enhancement: Record Button, see #25 and 25e43cadb9369c48bca294ba607c2263433d34c6
- [x] Optimize launch order and callback of sub-threads and -processes, see #26 and 8b22ad99d4f2a8ac4721459fa8fcba2aee406d4f
- [x] Improve processes for interpreter/server, see #28 and d121a05370a0326efa6321952f8dbd9a8ffc40e7
- [x] XY-Stage behaviour: stage should have method to pass a `zmq.Context()` instance to, in order to publish data, see 211007ab9a871cbff1482e9f9feab1921d1d574e
- [x] XY stage should be aware of the movements and write them down in a file, see 211007ab9a871cbff1482e9f9feab1921d1d574e
- [x] If no special answer is needed, the server / stage should answer to each command with a generic answer containing various infos, see `movement_tracker` in 211007ab9a871cbff1482e9f9feab1921d1d574e
- [x] Separate `Worker` class into `ThreadWorker` and `QtWorker` in order to use it to get traceback in threads of server
